### ISSUE TITLE
Migrate CI testing to GitHub Actions

### ISSUE THREAD

**Issue by skalee** [riboseinc/enprot#10]
_@ronaldtse in https://github.com/riboseinc/enprot/pull/9#issuecomment-536485199:_
> yes, we're going to abandon Travis. It was one of @dewyatt 's dream.

I suppose no one will oppose if I'll do it all.

**Comment by ronaldtse** [comment]
@skalee please go ahead, thanks!

**Comment by skalee** [comment]
@ronaldtse FYI I've just experienced a silent half an hour long outage of GitHub Actions.

See https://github.com/riboseinc/enprot/commit/b5412f2a182dd101c9fb0597a49bd4c216eab5d4/checks, no trace of "Tests" workflow, which was defined in this commit. The workflow file was the same as in https://github.com/riboseinc/enprot/commit/9cd2ff4f707263640cf99b10637619e0257ff9cd/checks, so it wasn't a syntax error. Actually, trees on both commits are identical.

**Comment by skalee** [comment]
Done in #12.

**Comment by ronaldtse** [comment]
Thanks @skalee!
