### ISSUE TITLE
Supporting AES-GCM-SIV

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/enprot#13]
Certainly AEAD modes should be available to be used in Enprot. AES-GCM-SIV is one of them.

cc: @celic

**Comment by ronaldtse** [comment]
Now linked to https://github.com/randombit/botan/issues/2221 .

**Comment by dewyatt** [comment]
IIRC I did actually implement this using the `aes_gcm_siv` crate as a temporary solution until the botan side of things is done. I need to jump back to that and get it cleaned up before it gets too stale.

**Comment by ronaldtse** [comment]
👍
