### ISSUE TITLE
KEY vs password terminology

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/enprot#16]
I think users are familiar with the term "password", but we currently use the term "key" in a similar fashion:

```
        -k WORD=KEY     Specify a secret KEY for WORD.
```

I personally find this to be confusing and think "password" is more conventional. We do something similar in the code (see `get_key`, which actually gets a password).  Is there any interest in changing this?

**Comment by ronaldtse** [comment]
Agree, it’s confusing. Password or Passphrase? Password probably easier to understand.
