### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/enprot#17]
Right now, for accurate results, we may have to wait on:
https://github.com/xd009642/tarpaulin/issues/105

The integration tests I've written (not yet committed) use `assert_cmd` (successor to `assert_cli`).

**Comment by dewyatt** [comment]
We might also want to try https://github.com/mozilla/grcov as an alternative and see how well it works with `assert_cmd`.

**Comment by ronaldtse** [comment]
Agree, let’s try grcov.
