### ISSUE TITLE
Weak key derivation

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/enprot#3]
The current key derivation is a plain SHA3-512 on the password, which is not really suitable for password-based key derivation.

I would propose to change the default to something like Argon2 and additionally add support for PBKDF2 (required for FIPS anyway), deprecating the current derivation.

This would likely require some changes to the markup but I think it can be done in a backwards-compatible way.

@ronaldtse What do you think?

**Comment by dewyatt** [comment]
Also this means that using the same password to encrypt the same plaintext will result in the same ciphertext.
IOW an attacker could surmise that two encrypted sections contain identical plaintext.

I think another contributing factor is that no nonce AAD is used for the AES-256-SIV encryption [here](https://github.com/riboseinc/enprot/blob/75f9c2b6853bce69a42f45c0fb86466edb54e407/src/prot.rs#L33).

EDIT: Thinking about this again though, I could see that this particular point might be a feature and not a bug in some ways, considering the goals of enprot, the design of CAS, etc.

**Comment by dewyatt** [comment]
@ronaldtse ping

**Comment by ronaldtse** [comment]
@dewyatt Darn I thought I replied to this but probably forgot to submit the comment...

Indeed, this was originally a feature, but you're also right about key derivation especially when the password is entered in the command line to enprot. So the proposal does make sense, especially for FIPS.

**Comment by dewyatt** [comment]
What I've worked on so far looks like this:

Old:
```
// <( ENCRYPTED agent007 4765d44ad1e0ebeb66be1bc71672b572fc98c52bfa7cf8e9cf5d0b1be978d712  )>
```

Proposed:
```
// <( ENCRYPTED agent007 07edbc5fb94549e544c7ff91676e634068df3fd3627bb1598511c7622da21ebc $pbkdf2-sha256$i=92000$NELxqwxlxtQ )>
```

Old:
```
// <( ENCRYPTED agent007  )>
// <( DATA CrhET0SXM1UY0KkbCpjl3g8Qp1nQTVB8sDeu2UNvqw== )>
// <( END agent007 )>
```

Proposed:
```
// <( ENCRYPTED agent007 $pbkdf2-sha256$i=90000$POTI5wXnmZM )>
// <( DATA FALJpS4fshVEHVMN7gFyeFybFZda8K4ldpui28mD8w== )>
// <( END agent007 )>
```

This would be backwards-compatible. It's a bit verbose maybe but flexible.
What do you think?

I've also been looking at adding AES-GCM in addition to AES-SIV. It's not deterministic so I'm thinking of doing some key wrapping, so that the same encrypted text (w/same pass) will be a single entry in CAS. Still looking into this.

**Comment by dewyatt** [comment]
ping @ronaldtse

**Comment by ronaldtse** [comment]
@dewyatt my only concern is about the user experience on how this would work.

For example, a text file starts off like this:

```
hello, this is a test file
// <( BEGIN Agent_007 )>
Super secret line 3
// <( END Agent_007 )>
```

Then it gets transformed into this:

```
hello, this is a test file
// <( BEGIN Agent_007 {key-algo-nonce-etc} )>
// <( DATA askdjhakdjshkasjdhkasjhd )>
// <( END Agent_007 )>
```

Correct? If so it looks fine to me.

**Comment by dewyatt** [comment]
@ronaldtse Correct. Ok I'll start implementing it in the rust code base this week.

**Comment by ronaldtse** [comment]
Excellent @dewyatt , thanks!
