### ISSUE TITLE
Add a fips flag

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/enprot#30]
As discussed: https://github.com/riboseinc/enprot/pull/29#issuecomment-562672399

This should also be set automatically on Linux when `fips_enabled` is set.

**Comment by ronaldtse** [comment]
FIPS algorithms: https://crypto.stackexchange.com/questions/3859/fips-140-2-compliant-algorithms

**Comment by dewyatt** [comment]
> FIPS algorithms: https://crypto.stackexchange.com/questions/3859/fips-140-2-compliant-algorithms

Yep that's one of my 100 browser tabs I have open on this somewhere. :(
I'm pretty sure I already implemented the `fips_enabled` bit too, I just need to focus on individual tasks and get them to completion. I have too many half-done things sitting around (partially from being on the road too much, but I've been home for a few weeks now).

140-3 is in the works too but that will be a while as I'm sure you're aware.

**Comment by ronaldtse** [comment]
140-3 seems to be some time away and I was told we should do 140-2. I await the day clearing off all my browser tabs, too.

**Comment by dewyatt** [comment]
https://github.com/riboseinc/enprot/pull/46
