### ISSUE TITLE
CI: Do auto-release using GHA

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/enprot#32]
It's time for enprot to be automatically released on Crates and also via the GH Releases page.

**Comment by dewyatt** [comment]
Before we can publish to crates.io, I think we need to be using versioned releases of the `phc` and `phf` crates. Currently we are using git HEAD for those for various reasons. So we'll need to address that first.

**Comment by dewyatt** [comment]
@ronaldtse I took care of `phf` in https://github.com/riboseinc/enprot/pull/35. For `phc` I created an issue to inquire about a new release: https://github.com/kstrohbeck/phc/issues/1. We'll have to see if the author responds.

**Comment by ronaldtse** [comment]
Ooo hope `phc` could be released as a proper dependency soon!

**Comment by dewyatt** [comment]
The author of the phc crate has kindly created a new suitable release. :)
So I'll get to working on this.

**Comment by ronaldtse** [comment]
Fantastic! It will be packaging time soon 👍

**Comment by dewyatt** [comment]
> error: api errors (status 200 OK): A verified email address is required to publish crates to crates.io. Visit https://crates.io/me to set and verify your email address.

@ronaldtse can you help with this?

**Comment by ronaldtse** [comment]
@dewyatt done!

**Comment by dewyatt** [comment]
Ok `cargo install enprot` is now working. There was some sort of bug with `cargo publish` that seemed to try to pull in binaries or botan's source which bloated the crate beyond the 10MB limit. Anyways, tested fine on macOS and Arch.
