### ISSUE TITLE
Modularize CAS

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/enprot#4]
The CAS is currently limited to a filesystem-backed storage system.
It may be helpful to also support some plain memory-backed storage (easier unit tests, etc).

**Comment by skalee** [comment]
How about mounting a tmpfs file system at CAS path? Not the most user-friendly solution, certainly not a cross-platform one, but perhaps good enough one?

**Comment by dewyatt** [comment]
Honestly I already added basic tests and it wasn't hindered much by this issue, so I can probably close this.

**Comment by ronaldtse** [comment]
Thanks guys !
