### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/enprot#5]
I'll be pushing tests fairly soon (still cleaning up and reordering commits for #3), so we ought to add a quick `cargo test` call in Travis after that.

(Creating this issue so I don't forget)

**Comment by ronaldtse** [comment]
Exciting stuff, can’t wait :wink:

**Comment by skalee** [comment]
I suppose it has been resolved in #7. Maybe we could also use a Travis CI badge in the README.

**Comment by ronaldtse** [comment]
Indeed, thanks @dewyatt for the tests and @skalee for closing 👍
